language: cpp

env:
  global:
    - CTEST_PARALLEL_LEVEL=4
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  include:
    - dist: trusty
      compiler: gcc
    - dist: xenial
      compiler: gcc
    - dist: xenial
      compiler: clang
    - os: osx
      compiler: clang

install:
  # Install dependencies for FCL
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 'ci/install_linux.sh' ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 'ci/install_osx.sh'   ; fi

script:
  # Create build directory
  - mkdir build
  - cd build

  # Configure
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-w ..

  # Build
  - make -j4

  # Run unit tests
  - make test

  # Make sure we can install and uninstall with no issues
  - sudo make -j4 install
  - sudo make -j4 uninstall
